package(default_visibility = ["//visibility:public"])

cc_library(
    name = "window",
    hdrs = ["window.hpp"],
    srcs = ["window.cpp"],
    deps = ["//src/templates:singleton", "//include:glad", "//lib:glfw"],
)