package(default_visibility = ["//visibility:public"])

cc_import(
    name = "glfw",
    hdrs = ["glfw3.h", "glfw3native.h"],
    shared_library = "glfw3.dll",
    alwayslink = True,
)

cc_import(
    name = "opengl32",
    shared_library = "opengl32.dll",
    alwayslink = True,
)