package(default_visibility = ["//visibility:public"])

cc_library(
    name = "glad",
    hdrs = ["glad.h"],
    srcs = ["glad.c"],
    deps = [":khrplatform"],
    linkstatic = False,
)

cc_library(
    name = "khrplatform",
    hdrs = ["khrplatform.h"],
)